// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1MrspyUCqeVg7VjbMSviGwFUQ8peyX5o',
    appId: '1:807933314174:web:7a0b69062797c200f6042f',
    messagingSenderId: '807933314174',
    projectId: 'laapata-5c186',
    authDomain: 'laapata-5c186.firebaseapp.com',
    storageBucket: 'laapata-5c186.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI8PthsRxwbDZbd5n6xk5SajrUR676RMo',
    appId: '1:807933314174:android:beda01708eeedaacf6042f',
    messagingSenderId: '807933314174',
    projectId: 'laapata-5c186',
    storageBucket: 'laapata-5c186.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8rYwGPKFxMHGjbrE-DLidWiDd5MK1dAM',
    appId: '1:807933314174:ios:99cb80be072a3bcdf6042f',
    messagingSenderId: '807933314174',
    projectId: 'laapata-5c186',
    storageBucket: 'laapata-5c186.appspot.com',
    iosClientId: '807933314174-ggubu19dd6t6ccoi35sufbdie2e293fu.apps.googleusercontent.com',
    iosBundleId: 'com.findmissingperson.findMissingPeople',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8rYwGPKFxMHGjbrE-DLidWiDd5MK1dAM',
    appId: '1:807933314174:ios:095b80adeceb38c5f6042f',
    messagingSenderId: '807933314174',
    projectId: 'laapata-5c186',
    storageBucket: 'laapata-5c186.appspot.com',
    iosClientId: '807933314174-umgu0kg6iu01i14kr9vq86cq2gtce5ti.apps.googleusercontent.com',
    iosBundleId: 'com.findmissingperson.findMissingPeople.RunnerTests',
  );
}
